version: '3.1'
services:
  web:
    container_name: server-api-flask
    hostname: server-api-flask
    build: ./api-consulta-b3
    ports:
      - 5001:5000
    volumes:
      - ./api-consulta-b3:/code
    networks:
      - pipeline-data-net
  
  zookeeper:
      hostname: zookeeper
      container_name: zookeeper-nifi
      image: 'bitnami/zookeeper:latest'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      networks:
        - pipeline-data-net
      volumes:
        - ./data/zookeeper:/datalog

  nifi:
    image: pettenge/nifi-arm64
    container_name: nifi-arm64
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper-nifi:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    networks:
      - pipeline-data-net
    volumes:
      - ./data/nifi:/nifi
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ËS_JAVA_OPTS=xms512m - Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - pipeline-data-net
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/certs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    container_name: kibana
    hostname: kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://x.x.x.x:9200
    networks:
      - pipeline-data-net
    volumes:
      - ./data/kibana:/usr/share/kibana/data
  
  anaconda:
    hostname: anaconda
    container_name: anaconda
    image: continuumio/anaconda3
    build: ./data/anaconda
    ports:
      - 8888:8888
      - 6006:6006
    networks:
      - pipeline-data-net
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root
    tty: true
    volumes:
      - ./data/anaconda/notebooks:/opt/notebooks
      
networks:
  pipeline-data-net:
    driver: bridge